apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u15w72eyw-go
  janus-idp.io/tekton: u15w72eyw-go
  backstage.io/kubernetes-id: u15w72eyw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u15w72eyw-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
